version: '3'
services:
  database:
    image: alpine  # Use a lightweight image, as SQLite3 is included in Alpine Linux
    volumes:
      - ./djackets_django/db.sqlite3:/app/db.sqlite3  
  backend:
    build:
      context: .
      dockerfile: ./djackets_django/Dockerfile
    ports:
      - "8000:8000"  # Expose the backend service on port 8000
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
    volumes:
      - ./djackets_django:/code  # Mount your backend code as a volume
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: ./djackets_vue/Dockerfile
    ports:
      - "8080:8080"  # Expose the frontend service on port 8080
    volumes:
      - .:/app


