version: '3'

services:

  backend:
    build:
      context: ./djackets_django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"  # Expose the backend service on port 8000
    volumes:
      - ./djackets_django/dbsqlite3:/code/dbsqlite3

  frontend:
    build:
      context: ./djackets_vue
    command: npm run serve
    ports:
      - "8080:8080"  # Expose the frontend service on port 8080